export const PORTFOLIOS = [
  {
    name: "Depo Yönetimi",
    name_t: "depo_yonetim",
    logo: "/images/logo/crewin.svg",
    view_img: "/images/portfolio/depoYonetim/depoYonetim-banner.png",
    color_primary: "#012030",
    color_secondary: "#134E70",
    color_three: "",
    url: null,
    logo_design: false,
    web_design: false,
    mobile_design: true,
    coding: false,
    ai: false,
    figma: true,
    react: false,
    next: false,
  },
  {
    name: "Crewin Web",
    name_t: "crewin_web",
    logo: "/images/logo/crewin.svg",
    view_img: "/images/portfolio/crewin/crewin-banner.png",
    color_primary: "#012030",
    color_secondary: "#134E70",
    color_three: "",
    url: "https://crewin.org",
    logo_design: true,
    web_design: true,
    mobile_design: false,
    coding: true,
    ai: true,
    figma: true,
    react: false,
    next: true,
  },
  {
    name: "Crewin Mobile",
    name_t: "crewin_mobile",
    logo: "/images/logo/crewin.svg",
    view_img: "/images/portfolio/crewin-mobil/crewin-mobil-banner.png",
    color_primary: "#012030",
    color_secondary: "#134E70",
    color_three: "",
    url: null,
    logo_design: true,
    web_design: false,
    mobile_design: true,
    coding: false,
    ai: true,
    figma: true,
    react: false,
    next: false,
  },
  {
    name: "Casa Alegre Alaçatı",
    name_t: "casaalegrealacati",
    logo: "/images/logo/casaalegrealacati.svg",
    view_img: "/images/portfolio/casaalegrealacati/casaalegrealacati-banner.png",
    color_primary: "#d5bf87",
    color_secondary: "#5898AB",
    color_three: "#1B1E31000",
    url: "casaalegrealacati.com",
    logo_design: false,
    web_design: true,
    mobile_design: false,
    coding: true,
    ai: false,
    figma: true,
    react: true,
    next: false,
  },
  {
    name: "CrewNature",
    name_t: "crewnature",
    logo: "/images/logo/crewnature.svg",
    view_img: "/images/portfolio/crewNature/crewNature-banner.png",
    color_primary: "#8200f4",
    color_secondary: "#15364C",
    color_three: "",
    url: "crewnature.com",
    logo_design: true,
    web_design: true,
    mobile_design: false,
    coding: true,
    ai: true,
    figma: true,
    react: true,
    next: false,
  },
  {
    name: "Karacoban Eng",
    name_t: "karacoban",
    logo: "/images/logo/karacobaneng.svg",
    view_img: "/images/portfolio/karacobaneng/karacobaneng-banner.png",
    color_primary: "#003851",
    color_secondary: "#009AC4",
    color_three: "#D9D9D9",
    url: "karacobaneng.com",
    logo_design: true,
    web_design: true,
    mobile_design: false,
    coding: true,
    ai: true,
    figma: true,
    react: true,
    next: false,
  },
];
