"use client";
import Navbar from "@/components/Navbar/Navbar";
import Sidebar from "../components/Sidebar/Sidebar";
import SocialMedias from "../components/SocialMedias/SocialMedias";
import "../styles/globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Navbar />
          {/* <Sidebar /> */}
          {/* <SocialMedias /> */}
          <main className="w-full md:mx-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
