"use client";
import type { Metadata } from "next";
import "./styles/globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import {
  Bezier,
  Brush,
  Brush2,
  Gallery,
  Layer,
  Play,
  Text,
} from "iconsax-react";
import EntryIconCard from "./components/EntryIconCard/EntryIconCard";
import { motion } from "framer-motion";
import SocialMedias from "./components/SocialMedias/SocialMedias";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
          <SocialMedias/>
          <main className="w-full mx-6">
              {children}
          </main>
        </div>
      </body>
    </html>
  );
}
